name: Hotel Price Tracker

on:
  schedule:
    - cron: "0 */12 * * *" # "At minute 0 past every 12th hour." (https://crontab.guru/)

jobs:
  execute:
    environment: production
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: GCP Auth
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: '${{ vars.GCP_WIP }}'
          service_account: '${{ secrets.GCP_SA }}'
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Update packages
        run: |
          sudo apt update
          sudo apt upgrade
      - name: Install newer Chromium
        run: sudo apt install -y chromium-browser
      - name: Installed package list
        run: apt list --installed
      - name: Install Python dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r hotel_prices/requirements.txt
      - name: Show Python dependencies
        run: |
            pip freeze
      - id: output_path
        name: Set output path
        run: echo "GCS_RAW_PATH='gs://${{ vars.GCS_BUCKET }}/personal-automation/hotel_prices/raw/seven-stars'" >> "$GITHUB_OUTPUT" \
          && echo "GCS_AGG_PATH='gs://${{ vars.GCS_BUCKET }}/personal-automation/hotel_prices/parquet'" >> "$GITHUB_OUTPUT"
      - name: Execute collection
        run: |
          python hotel_prices/main.py collect \
          --output-path=${{ steps.output_path.outputs.GCS_RAW_PATH }} \
          --start-date="04/01/2024" --stop-date="04/08/2024"
      - name: Execute aggregation
        run: |
          python hotel_prices/main.py aggregate \
          --input-path=${{ steps.output_path.outputs.GCS_RAW_PATH }} \
          --output-path=${{ steps.output_path.outputs.GCS_AGG_PATH }}
      - name: Execute analysis
        run: |
          python hotel_prices/main.py analyze \
          --input-path=${{ steps.output_path.outputs.GCS_AGG_PATH }} \
          --webook-url=${{ secrets.SLACK_WEBHOOK_URL }} \
          --member-ids='${{ secrets.SLACK_MEMBER_IDS }}'
